let products=[],cart=JSON.parse(localStorage.getItem('ajob_cart')||'[]'),cfg={},lang='en';
const $=id=>document.getElementById(id),money=n=>'৳'+Number(n||0).toLocaleString('en-BD');
async function api(u,o={}){const r=await fetch(u,{headers:{'Content-Type':'application/json',...(o.headers||{})},...o});return r.json()}
async function load(){cfg=await api('/api/settings');$('aboutText').textContent=cfg.about_store||'';for(const k of ['instagram','facebook','tiktok','whatsapp']){const v=cfg[k+'_link'];$(k).href=v||'#';$(k).style.opacity=v?'1':'.45'}loadProducts()}
async function loadProducts(){const q=$('search').value||'';products=await api('/api/products?search='+encodeURIComponent(q));render()}
function render(){const el=$('products');el.innerHTML=products.map(p=>`<article class="card"><img src="/assets/${p.image||'product-1.jpg'}"><div class="cat">${p.category||''}</div><h3>${esc(p.name)}</h3><div class="price">${money(p.price)}</div><button class="add" onclick="add(${p.id})">🛒 Add to Cart</button></article>`).join('')}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function add(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;const x=cart.find(x=>x.id==id);x?x.qty++:cart.push({id:p.id,name:p.name,price:Number(p.price),qty:1});localStorage.setItem('ajob_cart',JSON.stringify(cart));updateCart()}
function updateCart(){$('cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);$('cartItems').innerHTML=cart.length?cart.map(x=>`<div class="agentRow"><span>${esc(x.name)} × ${x.qty}</span><b>${money(x.price*x.qty)}</b></div>`).join(''):'<p>Your cart is empty.</p>'}
function closeCart(){$('cart').classList.remove('open')}
function checkout(){if(!cart.length)return alert('Your cart is empty.');const name=prompt('Your name');if(!name)return;const phone=prompt('Phone number');if(!phone)return;const address=prompt('Delivery address');if(!address)return;const total=cart.reduce((s,x)=>s+x.price*x.qty,0);api('/api/orders',{method:'POST',body:JSON.stringify({name,phone,address,items:cart,total})}).then(r=>{if(r.ok){alert('Order confirmed: '+r.order_code);cart=[];localStorage.setItem('ajob_cart','[]');updateCart();closeCart()}else alert(r.error||'Order failed')})}
function filterCat(c){$('search').value=c;loadProducts()}
function toggleChat(){$('chat').classList.toggle('open')}
function setLang(x){lang=x;const inp=$('chatInput');inp.placeholder=x==='bn'?'আপনার প্রশ্ন লিখুন...':'Type your message...';}
async function sendChat(){const input=$('chatInput'),text=input.value.trim();if(!text)return;addMsg(text,'user');input.value='';const ps=products;let reply='';const t=text.toLowerCase();const bn=lang==='bn'||/[\u0980-\u09ff]/.test(text);if(/hello|hi|hey|হাই|হ্যালো/.test(t))reply=bn?'হ্যালো! Ajob Data সম্পর্কে কী জানতে চান?':'Hello! What would you like to know about Ajob Data?';else if(/delivery|shipping|ডেলিভারি|কতদিন/.test(t))reply=bn?`ডেলিভারি সময় ${cfg.delivery_time||'2–5 business days'} এবং চার্জ ${cfg.delivery_fee||'৳80'}।`:`Delivery takes ${cfg.delivery_time||'2–5 business days'} and the delivery fee is ${cfg.delivery_fee||'৳80'}.`;else if(/payment|pay|পেমেন্ট|মূল্য পরিশোধ/.test(t))reply=bn?(cfg.payment_info||'Cash on Delivery and online payment available.'):(cfg.payment_info||'Cash on Delivery and online payment are available.');else if(/about|store|দোকান|স্টোর|ajob/.test(t))reply=cfg.about_store||defaults?.about_store||'';else if(/agent|contact|যোগাযোগ|এজেন্ট/.test(t)){const a=await api('/api/agents');reply=bn?'আমাদের active agent-দের সাথে যোগাযোগ করতে Agent Contact button ব্যবহার করুন।':'Use the Agent Contact button to contact an active Ajob Data support agent.';}else{const hits=ps.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(t)).slice(0,4);if(hits.length)reply=(bn?'পাওয়া গেছে: ':'Found: ')+hits.map(p=>`${p.name} — ${money(p.price)}${Number(p.stock)<=0?' (out of stock)':''}`).join('\n');else if(/price|দাম|কত|cost/.test(t))reply=bn?'কোন product-এর দাম জানতে চান? নাম লিখুন।':'Which product price would you like to know? Type its name.';else reply=bn?'আমি শুধু Ajob Data-এর products, prices, stock, delivery, payment, orders এবং store information নিয়ে সাহায্য করতে পারি।':'I can only help with Ajob Data products, prices, stock, delivery, payment, orders, and store information.'}addMsg(reply,'bot')}
function addMsg(t,c){const p=document.createElement('p');p.className=c;p.textContent=t;$('chatBody').appendChild(p);$('chatBody').scrollTop=$('chatBody').scrollHeight}
async function openAgents(){const a=await api('/api/agents');$('agentList').innerHTML=a.length?a.map(x=>`<div class="agentRow"><div><b>${esc(x.name)}</b><small style="display:block;color:#999">${esc(x.phone||'')}</small></div><a target="_blank" href="https://wa.me/${String(x.whatsapp||x.phone||'').replace(/\D/g,'')}">WhatsApp →</a></div>`).join(''):'No active agents';$('agentModal').classList.add('show')}
function closeAgents(){$('agentModal').classList.remove('show')}
document.addEventListener('DOMContentLoaded',()=>{load();updateCart();document.querySelector('.topright').addEventListener('click',()=>{$('cart').classList.add('open')})});
