const express=require('express');
const path=require('path');
const crypto=require('crypto');
const {createClient}=require('@libsql/client');
const app=express();
app.use(express.json({limit:'2mb'}));
const PORT=process.env.PORT||3000;
const dbUrl=process.env.TURSO_DATABASE_URL;
const token=process.env.TURSO_AUTH_TOKEN;
if(!dbUrl||!token){console.warn('TURSO_DATABASE_URL/TURSO_AUTH_TOKEN not configured. Configure them on Render before production use.');}
const db=(dbUrl&&token)?createClient({url:dbUrl,authToken:token}):null;
const defaults={
 store_name:'Ajob Data', store_tagline:'Electric Products • Smart Choices • Better Life', about_store:'Ajob Data brings trusted electric products and smart home solutions together in one premium destination.',
 delivery_time:'2–5 business days', delivery_fee:'৳80', cod_enabled:'true', payment_info:'Cash on Delivery and online payment are available.',
 instagram_link:'',facebook_link:'',tiktok_link:'',whatsapp_link:'', demo_seeded:'false'
};
const products=[
 ['Smart LED TV 43"','Home Appliances',24999,'4K smart LED TV with vivid display.','product-1.jpg'],['Refrigerator 300L','Home Appliances',42999,'Energy-efficient 300L refrigerator.','product-2.jpg'],['Washing Machine 7kg','Home Appliances',34999,'Modern 7kg automatic washing machine.','product-3.jpg'],['Air Conditioner 1.5 Ton','Cooling & Heating',49999,'Fast cooling 1.5 ton inverter AC.','product-4.jpg'],['Microwave Oven','Kitchen Appliances',12999,'Compact digital microwave oven.','product-5.jpg'],['Induction Cooker','Kitchen Appliances',7499,'Fast and safe induction cooking.','product-6.jpg'],['Ceiling Fan','Cooling & Heating',5499,'High-airflow premium ceiling fan.','product-7.jpg'],['LED Bulb (Pack of 5)','Lighting & Electrical',899,'Long-life energy-saving LED bulbs.','product-8.jpg'],['Power Strip','Accessories',1299,'Surge-protected multi-socket power strip.','product-9.jpg'],['Electric Drill','Power Tools',3499,'Corded electric drill for home projects.','product-10.jpg'],['Iron Box','Home Appliances',2499,'Non-stick soleplate steam iron.','product-11.jpg'],['Water Heater','Home Appliances',8999,'Compact instant electric water heater.','product-12.jpg']
];
async function init(){if(!db)return;await db.execute(`CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT)`);await db.execute(`CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,price REAL,description TEXT,image TEXT,stock INTEGER DEFAULT 10,active INTEGER DEFAULT 1)`);await db.execute(`CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,phone TEXT,whatsapp TEXT,active INTEGER DEFAULT 1)`);await db.execute(`CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,order_code TEXT UNIQUE,name TEXT,phone TEXT,address TEXT,items TEXT,total REAL,status TEXT DEFAULT 'Pending',created_at TEXT)`);for(const [k,v] of Object.entries(defaults)){await db.execute({sql:'INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)',args:[k,v]});}const c=await db.execute('SELECT COUNT(*) c FROM products');if(Number(c.rows[0].c)===0){for(const p of products)await db.execute({sql:'INSERT INTO products(name,category,price,description,image,stock,active) VALUES(?,?,?,?,?,?,1)',args:[...p,10]});}const a=await db.execute('SELECT COUNT(*) c FROM agents');if(Number(a.rows[0].c)===0)await db.execute({sql:'INSERT INTO agents(name,phone,whatsapp,active) VALUES(?,?,?,1)',args:['Ajob Data Support','01700000000','8801700000000']});}
async function settings(){const r=await db.execute('SELECT key,value FROM settings');const o={...defaults};for(const x of r.rows)o[x.key]=x.value;return o;}
function auth(req,res,next){const h=req.headers.authorization||'';if(h==='Bearer '+(process.env.ADMIN_PASSWORD||''))return next();res.status(401).json({error:'Unauthorized'});}
app.get('/api/settings',async(req,res)=>{if(!db)return res.json(defaults);res.json(await settings())});
app.get('/api/products',async(req,res)=>{if(!db)return res.json([]);const q=String(req.query.search||'').trim();const r=q?await db.execute({sql:`SELECT * FROM products WHERE active=1 AND (name LIKE ? OR category LIKE ? OR description LIKE ?) ORDER BY id DESC`,args:[`%${q}%`,`%${q}%`,`%${q}%`]}):await db.execute('SELECT * FROM products WHERE active=1 ORDER BY id DESC');res.json(r.rows)});
app.get('/api/agents',async(req,res)=>{if(!db)return res.json([]);res.json((await db.execute('SELECT * FROM agents WHERE active=1')).rows)});
app.post('/api/orders',async(req,res)=>{if(!db)return res.status(503).json({error:'Database not configured'});const {name,phone,address,items,total}=req.body;if(!name||!phone||!address||!items?.length)return res.status(400).json({error:'Missing order details'});const code='AJD-'+Date.now().toString(36).toUpperCase();await db.execute({sql:'INSERT INTO orders(order_code,name,phone,address,items,total,status,created_at) VALUES(?,?,?,?,?,?,?,?)',args:[code,name,phone,address,JSON.stringify(items),Number(total||0),'Pending',new Date().toISOString()]});res.json({ok:true,order_code:code})});
app.get('/api/order/:code',async(req,res)=>{if(!db)return res.status(503).json({error:'Database not configured'});const r=await db.execute({sql:'SELECT order_code,name,total,status,created_at FROM orders WHERE order_code=?',args:[req.params.code]});if(!r.rows.length)return res.status(404).json({error:'Order not found'});res.json(r.rows[0])});
app.post('/api/admin/settings',auth,async(req,res)=>{for(const [k,v] of Object.entries(req.body||{})){if(!/^[a-z_]+$/.test(k))continue;await db.execute({sql:'INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',args:[k,String(v)]});}res.json({ok:true})});
app.get('/api/admin/products',auth,async(req,res)=>res.json((await db.execute('SELECT * FROM products ORDER BY id DESC')).rows));
app.post('/api/admin/products',auth,async(req,res)=>{const p=req.body;await db.execute({sql:'INSERT INTO products(name,category,price,description,image,stock,active) VALUES(?,?,?,?,?,?,?)',args:[p.name,p.category,Number(p.price),p.description||'',p.image||'product-1.jpg',Number(p.stock||0),p.active===false?0:1]});res.json({ok:true})});
app.put('/api/admin/products/:id',auth,async(req,res)=>{const p=req.body;await db.execute({sql:'UPDATE products SET name=?,category=?,price=?,description=?,image=?,stock=?,active=? WHERE id=?',args:[p.name,p.category,Number(p.price),p.description||'',p.image||'product-1.jpg',Number(p.stock||0),p.active===false?0:1,req.params.id]});res.json({ok:true})});
app.delete('/api/admin/products/:id',auth,async(req,res)=>{await db.execute({sql:'DELETE FROM products WHERE id=?',args:[req.params.id]});res.json({ok:true})});
app.get('/api/admin/orders',auth,async(req,res)=>res.json((await db.execute('SELECT * FROM orders ORDER BY id DESC')).rows));
app.put('/api/admin/orders/:id',auth,async(req,res)=>{await db.execute({sql:'UPDATE orders SET status=? WHERE id=?',args:[req.body.status,req.params.id]});res.json({ok:true})});
app.get('/api/admin/agents',auth,async(req,res)=>res.json((await db.execute('SELECT * FROM agents ORDER BY id DESC')).rows));
app.post('/api/admin/agents',auth,async(req,res)=>{const a=req.body;await db.execute({sql:'INSERT INTO agents(name,phone,whatsapp,active) VALUES(?,?,?,?)',args:[a.name,a.phone,a.whatsapp,a.active===false?0:1]});res.json({ok:true})});
app.delete('/api/admin/agents/:id',auth,async(req,res)=>{await db.execute({sql:'DELETE FROM agents WHERE id=?',args:[req.params.id]});res.json({ok:true})});
app.get('/api/admin/dashboard',auth,async(req,res)=>{const [p,o,a]=await Promise.all([db.execute('SELECT COUNT(*) c FROM products'),db.execute('SELECT COUNT(*) c FROM orders'),db.execute('SELECT COUNT(*) c FROM agents')]);res.json({products:p.rows[0].c,orders:o.rows[0].c,agents:a.rows[0].c})});
app.use(express.static(path.join(__dirname,'public')));app.use('/admin',express.static(path.join(__dirname,'admin')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(PORT,()=>console.log('Ajob Data running on '+PORT))).catch(e=>{console.error(e);process.exit(1)});
